'use strict'; const assert = require('node:assert/strict'); const fs = require('node:fs'); const path = require('node:path'); const test = require('node:test');
test('A2A tasks have a dedicated UI and do not enter visitor conversations', () => { const source = fs.readFileSync(path.join(__dirname, '..', 'src', 'web', 'index.js'), 'utf8');
  assert.match(source, /R\.get\('\/a2a-tasks'/); assert.match(source, /a2a_local_tasks/); assert.match(source, /listOutboundTasks/);
  assert.match(source, /listInboundTasks/); assert.match(source, /\/api\/a2a\/tasks/); assert.match(source, /tab-a2a/);
  assert.match(source, /authorizeA2AApi/); assert.match(source, /WEB_AUTH_REQUIRED/); assert.match(source, /Context <code>/);
  assert.match(source, /renderA2APrincipalRows\(a2aPanelRows,agentId,T\)/);
  assert.match(source, /const showA2ATab=a2aReadAvailable&&a2aTotal>0/);
  assert.match(source, /showA2ATab\?tabBtn\('a2a'/);
  assert.match(source, /taskTableA2A\?renderA2ATaskRows/);
  assert.match(source, /buildA2APrincipalGroups\(a2aRows,T,a2aKeyword\)/);
  assert.match(source, /name="a2aKeyword"/);
  assert.match(source, /a2aPage/);
  assert.match(source, /web\.agent\.a2a\.search_ph/);
  assert.match(source, /web\.agent\.a2a\.col\.counterparty/);
  assert.doesNotMatch(source, /href="\/a2a-tasks" class="op-card"/);
  assert.doesNotMatch(source, />View A2A Tasks<\/a>/);
  const agentPanel = source.match(/const a2aPanel=.*?;\n/)[0];
  assert.doesNotMatch(agentPanel, /Agent Card|\/caps/);
  const detailRoute = source.match(/R\.get\('\/a2a-tasks\/:taskId'[\s\S]*?\n  \}\);/)[0];
  assert.match(detailRoute, /web\.a2a_task\.timeline/);
  assert.match(detailRoute, /renderFooter\(T,locale\)/);
  assert.match(source, /principal_display_id/);
  assert.match(source, /R\.get\('\/agents\/:agentId\/a2a\/:principalViewId'/);
  assert.match(source, /\^pv_\[0-9a-f\]\{32\}\$\/i/);
  assert.match(source, /web\.a2a_principal\.task_tab/);
  assert.match(source, /web\.a2a_principal\.conversation_title/);
  assert.match(source, /agentNav\(agentId,agent\?\.agentName\|\|agentId,T\)\+' › '\+esc\(principalDisplayId\)/);
  assert.doesNotMatch(source, /const counterpartyLabel=/);
  assert.match(source, /contextId='\+encodeURIComponent\(context\.id\)/);
  assert.match(source, /const key=principalViewId\|\|\('task:'\+String\(row\.task_id\)\)/);
  assert.match(source, /nav:agentNav\(agentId,agent\?\.agentName\|\|agentId,T\)/);
  assert.match(source, /CONVERSATION_TAB_CSS/);
  assert.match(source, /renderA2ATaskConversation\(task,principalDisplayId,T\)/);
  assert.match(source, /web\.a2a_principal\.context_tab/);
  assert.match(source, /api\/a2a\/agents\/:agentId\/principals\/:principalViewId\/contexts\/:contextId/);
  assert.match(source, /web\.a2a_task\.no_content/);
  assert.match(source, /web\.a2a_task\.no_reply/);
  assert.match(source, /payload\.noReply===true/);
  assert.match(source, /type==='task_submitted'/);
  const route = source.match(/R\.get\('\/a2a-tasks'[\s\S]*?\n  \}\);/)[0];
  assert.match(source, /isolated from visitor conversations/); assert.doesNotMatch(route, /FROM messages|FROM conversations|INSERT INTO messages/);
});
test('A2A tab is not rendered for an empty or unavailable task source', () => {
  const source = fs.readFileSync(path.join(__dirname, '..', 'src', 'web', 'index.js'), 'utf8');
  assert.match(source, /if\(requestedTab==='a2a'&&!showA2ATab\)/);
  assert.match(source, /a2aReadAvailable=false/);
  assert.match(source, /const a2aPanel=showA2ATab\?/);
});
