'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {DatabaseSync}=require('node:sqlite');
const {initOwnerChatSchema,createOwnerExecutionContext,transitionOwnerExecution,readOwnerChatPolicy,updateOwnerChatPolicy}=require('../build/owner-chat');
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'owner-exec-'));const db=new DatabaseSync(path.join(dir,'db.sqlite'));initOwnerChatSchema(db);db.prepare(`INSERT INTO owner_chat_messages
 (message_id,client_message_id,conversation_id,owner_identity_id,owner_im_uid,agent_id,local_agent_id,ownership_epoch,conversation_epoch,sequence,content_type,payload_json,payload_digest,state,execution_state,created_at,updated_at)
 VALUES('m','c','conversation','identity','owner-im','remote','local',1,1,1,1,'{"text":"hello"}','digest','persisted','PERSISTED',1,1)`).run();return{db,close(){db.close();fs.rmSync(dir,{recursive:true,force:true})}}}
test('Owner execution context is immutable and never part of message content',()=>{const value=createOwnerExecutionContext({conversationId:'c',messageId:'m',ownershipEpoch:2,conversationEpoch:3,policyEpoch:4,config:{provider:'codex'}});assert.equal(Object.isFrozen(value),true);assert.equal(value.authority,'verified_owner_conversation');assert.match(value.configDigest,/^[a-f0-9]{64}$/);assert.equal('content' in value,false)});
test('Owner execution state transitions are CAS guarded and audited',()=>{const f=fixture();try{assert.equal(transitionOwnerExecution(f.db,{messageId:'m',from:'PERSISTED',to:'DISPATCH_RESERVED',leaseOwner:'worker',leaseExpiresAt:99}),true);assert.equal(transitionOwnerExecution(f.db,{messageId:'m',from:'PERSISTED',to:'DISPATCH_RESERVED'}),false);assert.equal(transitionOwnerExecution(f.db,{messageId:'m',from:'DISPATCH_RESERVED',to:'OUTCOME_UNKNOWN',reasonCode:'timeout'}),true);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM owner_chat_execution_events').get().n,2);assert.throws(()=>transitionOwnerExecution(f.db,{messageId:'m',from:'OUTCOME_UNKNOWN',to:'PERSISTED'}),/TRANSITION_INVALID/)}finally{f.close()}});
test('global Owner Chat disable revokes pending work and cannot enable host access',()=>{const f=fixture();try{assert.equal(readOwnerChatPolicy(f.db).ownerChatEnabled,true);const policy=updateOwnerChatPolicy(f.db,{ownerChatEnabled:false,hostFullAccessEnabled:true});assert.equal(policy.ownerChatEnabled,false);assert.equal(policy.hostFullAccessEnabled,false);assert.equal(f.db.prepare("SELECT execution_state FROM owner_chat_messages WHERE message_id='m'").get().execution_state,'REVOKED')}finally{f.close()}});
