'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {DatabaseSync}=require('node:sqlite');
const {initOwnerChatSchema,OwnerChatOutbox,OwnerChatReadStore}=require('../build/owner-chat');

function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'owner-chat-read-'));const db=new DatabaseSync(path.join(dir,'chat.db'));initOwnerChatSchema(db);return{db,close(){db.close();fs.rmSync(dir,{recursive:true,force:true})}}}
function inbound(db,{id,conversation='c1',agent='a1',sequence=1,type=1,payload={text:'hello'},state='persisted',at=100}){db.prepare(`INSERT INTO owner_chat_messages
  (message_id,client_message_id,conversation_id,owner_identity_id,owner_im_uid,agent_id,local_agent_id,ownership_epoch,conversation_epoch,sequence,content_type,payload_json,payload_digest,state,created_at,updated_at)
  VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,id,conversation,'owner-id','owner-im','remote-agent',agent,1,1,sequence,type,JSON.stringify(payload),'digest-'+id,state,at,at)}
function reply(db,{id='r1',message='m1',conversation='c1',agent='a1',sequence=1,text='reply',status='sent',at=200,payload}){const envelope=payload||{kind:'reply',operation:'reply',sequence,contentType:1,payload:{replyToMessageId:message,text}};db.prepare(`INSERT INTO owner_chat_outbox
  (event_id,message_id,conversation_id,agent_id,local_agent_id,owner_im_uid,payload_json,status,created_at,updated_at)
  VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,message,conversation,'remote-agent',agent,'owner-im',JSON.stringify(envelope),status,at,at)}

test('read store lists only conversations for the requested Agent and combines replies',()=>{const f=fixture();try{inbound(f.db,{id:'m1'});reply(f.db,{});inbound(f.db,{id:'m2',conversation:'c2',sequence:1,at:300,payload:{text:'newer'}});inbound(f.db,{id:'other',agent:'a2',conversation:'hidden'});const store=new OwnerChatReadStore(f.db);assert.equal(store.countForAgent('a1'),2);assert.deepEqual(store.listForAgent('a1').map(row=>row.conversationId),['c2','c1']);const transcript=store.getTranscript('a1','c1');assert.deepEqual(transcript.map(row=>row.direction),['owner','agent']);assert.equal(transcript[1].payload.text,'reply');assert.deepEqual(store.getTranscript('a2','c1'),[]);}finally{f.close()}});

test('read store sanitizes unsafe payloads and skips malformed reply envelopes',()=>{const f=fixture();try{inbound(f.db,{id:'m1',type:3,payload:{name:'report.pdf',size:10,downloadUrl:'javascript:alert(1)',text:'note'}});reply(f.db,{payload:{kind:'reply',operation:'wrong',payload:{text:'secret signature'}}});const store=new OwnerChatReadStore(f.db);const transcript=store.getTranscript('a1','c1');assert.equal(transcript.length,1);assert.equal(transcript[0].payload.downloadUrl,undefined);assert.equal(transcript[0].payload.name,'report.pdf');}finally{f.close()}});

test('read store maps processing, failure and unknown outcomes',()=>{const f=fixture();try{inbound(f.db,{id:'m1',conversation:'processing'});inbound(f.db,{id:'m2',conversation:'failed',state:'failed_not_delivered'});inbound(f.db,{id:'m3',conversation:'unknown',state:'outcome_unknown'});const statuses=Object.fromEntries(new OwnerChatReadStore(f.db).listForAgent('a1',10,0).map(row=>[row.conversationId,row.status]));assert.equal(statuses.processing,'processing');assert.equal(statuses.failed,'failed');assert.equal(statuses.unknown,'outcome_unknown');}finally{f.close()}});

test('outbox reports the affected Agent and conversation after delivery state changes',async()=>{const f=fixture();try{inbound(f.db,{id:'m1'});reply(f.db,{status:'pending'});const updates=[];const outbox=new OwnerChatOutbox(f.db,{deliver:async()=>({success:true})},60000,event=>updates.push(event));assert.equal(await outbox.flush(),1);assert.deepEqual(updates,[{agentId:'a1',conversationId:'c1'}]);assert.equal(f.db.prepare('SELECT status FROM owner_chat_outbox WHERE event_id=?').get('r1').status,'sent');}finally{f.close()}});
