const {test}=require('node:test');const assert=require('node:assert/strict');const {DatabaseSync}=require('node:sqlite');
const {createProjectWorker}=require('../build/core/project-worker');
function fixture(t){const db=new DatabaseSync(':memory:');db.exec("CREATE TABLE agents(agent_id TEXT,publish_status TEXT);INSERT INTO agents VALUES('agent','published')");t.after(()=>db.close());return db;}
test('an explicit claimed execution returns a durable result without completing the business task',async t=>{
 const db=fixture(t);let claims=0,runs=0,finishes=0,queued=true,failFinish=true;
 const client=async(_a,_c,action,input)=>{let data={};if(action==='executionQueue')data={jobs:queued?[{id:'run',channel_id:'group'}]:[]};if(action==='executionClaim'){claims++;queued=false;data={task:{id:'task',title:'Task',description:'Goal'},messages:[],executions:[],assets:[],instructions:'',execution:{instruction:'Do this'}}}if(action==='storageGet')data={configuration:{bucket:'customer'}};if(action==='executionFinish'){finishes++;if(failFinish)return {status:503,body:{success:false,code:'PROJECT_UNAVAILABLE'}};assert.equal(input.status,'succeeded');assert.equal(input.result,'Done')};return{status:200,body:{success:true,data}}};
 const worker=createProjectWorker({db,client,dispatcher:{getAgentDeliveryStatus:()=>({automaticDeliveryReady:true}),executeIsolated:async options=>{runs++;assert.equal(options.sourceType,'external');assert.match(options.content,/Do this/);return{reply:{content:'Done'}}}}});
 await worker.tick();assert.equal(runs,1);assert.equal(db.prepare('SELECT state FROM project_execution_outbox').get().state,'result');failFinish=false;await worker.tick();assert.equal(runs,1);assert.equal(claims,1);assert.ok(finishes>=2);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM project_execution_outbox').get().n,0);
});
test('lost claim response never executes or silently reclaims',async t=>{const db=fixture(t);let claims=0,runs=0;const worker=createProjectWorker({db,dispatcher:{getAgentDeliveryStatus:()=>({automaticDeliveryReady:true}),executeIsolated:async()=>{runs++}},client:async(_a,_c,action)=>{if(action==='executionQueue')return{status:200,body:{success:true,data:{jobs:[{id:'run',channel_id:'group'}]}}};if(action==='executionClaim')claims++;return{status:503,body:{success:false,code:'PROJECT_UNAVAILABLE'}}}});await worker.tick();await worker.tick();assert.equal(runs,0);assert.equal(claims,1);assert.match(db.prepare('SELECT payload FROM project_execution_outbox').get().payload,/unknown/);});
test('blocked Provider output is never published in task results',async t=>{const db=fixture(t);let queued=true,published;const worker=createProjectWorker({db,safety:{assertAllowed:async(_text,direction)=>{if(direction==='outbound'){const e=new Error('blocked');e.name='A2ASafetyRejection';throw e}}},dispatcher:{getAgentDeliveryStatus:()=>({automaticDeliveryReady:true}),executeIsolated:async()=>({reply:{content:'BLOCKED_OUTPUT'}})},client:async(_a,_c,action,input)=>{let data={};if(action==='executionQueue')data={jobs:queued?[{id:'run',channel_id:'group'}]:[]};if(action==='executionClaim'){queued=false;data={task:{id:'task',title:'test',description:''},messages:[],executions:[],assets:[],execution:{instruction:'test'}}}if(action==='storageGet')data={configuration:{bucket:'test'}};if(action==='executionFinish')published=input;return{status:200,body:{success:true,data}}}});await worker.tick();assert.equal(published.status,'failed');assert.ok(!published.result.includes('BLOCKED_OUTPUT'));});

test('an unauthorized stale Agent does not starve the next Agent queue',async t=>{
 const db=fixture(t);db.exec("INSERT INTO agents VALUES('healthy','published')");const queried=[];
 const worker=createProjectWorker({db,dispatcher:{getAgentDeliveryStatus:()=>({automaticDeliveryReady:true})},client:async(agent,_channel,action)=>{
  assert.equal(action,'executionQueue');queried.push(agent);
  return agent==='agent'?{status:401,body:{success:false,code:'PROJECT_AGENT_AUTH_REQUIRED'}}:{status:200,body:{success:true,data:{jobs:[]}}};
 }});await worker.tick();assert.deepEqual(queried,['agent','healthy']);
});
